#Sevices

parameters:
    fantasyapi.key:  c0f84de6b37c459f9290dfc2f5526a05

services:
    #FantasyDataAPI Client
    fantasyapi:
        class:        FantasyDataAPI\Client
        arguments:    ["%fantasyapi.key%"]

    #Helpers
    date_helper:
        class:        FantasyPro\DataBundle\Helpers\DateHelper

    data_fetcher:
        class:        FantasyPro\DataBundle\Helpers\DataFetcher
        arguments:    [@fantasyapi]

    season_helper:
        class:        FantasyPro\DataBundle\Helpers\SeasonHelper
        arguments:    [@fantasyapi]
    # builders
    #The builders are called by the persiters, these builders are respnsible for setting up the data to be stored into the associated entities.
    byeBuilder:
        class:        FantasyPro\DataBundle\Builder\ByeBuilder

    dailyFantasyPlayerBuilder:
        class:        FantasyPro\DataBundle\Builder\DailyFantasyPlayerBuilder
        arguments:    [@date_helper]

    fantasyDefenseGameBuilder:
        class:        FantasyPro\DataBundle\Builder\FantasyDefenseGameBuilder
        arguments:    [@date_helper]

    fantasyDefenseSeasonBuilder:
        class:        FantasyPro\DataBundle\Builder\FantasyDefenseSeasonBuilder
        arguments:    [@date_helper]

    fantasyDefenceProjectionsByGameBuilder:
        class:        FantasyPro\DataBundle\Builder\FantasyDefenseProjectionsByGameBuilder
        arguments:    [@date_helper]

    fantasyDefenceProjectionsBySeasonBuilder:
        class:        FantasyPro\DataBundle\Builder\FantasyDefenseProjectionsBySeasonBuilder
        arguments:    [@date_helper]

    freeAgentBuilder:
        class:        FantasyPro\DataBundle\Builder\FreeAgentBuilder
        arguments:    [@date_helper]

    gameLeagueLeadersBuilder:
        class:        FantasyPro\DataBundle\Builder\GameLeagueLeadersBuilder
        arguments:    [@date_helper]

    gameStatsBySeasonBuilder:
        class:        FantasyPro\DataBundle\Builder\GameStatsBySeasonBuilder
        arguments:    [@date_helper]

    gameStatsByWeekBuilder:
        class:        FantasyPro\DataBundle\Builder\GameStatsByWeekBuilder
        arguments:    [@date_helper]

    injuryBuilder:
        class:        FantasyPro\DataBundle\Builder\InjuryBuilder
        arguments:    [@date_helper]

    newsBuilder:
        class:        FantasyPro\DataBundle\Builder\NewsBuilder
        arguments:    [@date_helper]

    playerBuilder:
        class:        FantasyPro\DataBundle\Builder\PlayerBuilder
        arguments:    [@date_helper]

    playerGameBuilder:
        class:        FantasyPro\DataBundle\Builder\PlayerGameBuilder
        arguments:    [@date_helper]

    boxPlayerGameBuilder:
        class:        FantasyPro\DataBundle\Builder\BoxPlayerGameBuilder
        arguments:    [@date_helper]

    playerGameProjectedStatsBuilder:
        class:        FantasyPro\DataBundle\Builder\PlayerGameProjectedStatsBuilder
        arguments:    [@date_helper]

    playerSeasonBuilder:
        class:        FantasyPro\DataBundle\Builder\PlayerSeasonBuilder
        arguments:    [@date_helper]

    playerSeasonProjectedBuilder:
            class:        FantasyPro\DataBundle\Builder\PlayerSeasonProjectedBuilder
            arguments:    [@date_helper]

    scheduleBuilder:
        class:        FantasyPro\DataBundle\Builder\ScheduleBuilder
        arguments:    [@date_helper]

    scoreBuilder:
        class:        FantasyPro\DataBundle\Builder\ScoreBuilder
        arguments:    [@date_helper]

    scoringDetailBuilder:
        class:        FantasyPro\DataBundle\Builder\ScoringDetailBuilder

    scoringPlayBuilder:
        class:        FantasyPro\DataBundle\Builder\ScoringPlayBuilder
        arguments:    [@date_helper]

    seasonLeagueLeadersBuilder:
        class:        FantasyPro\DataBundle\Builder\SeasonLeagueLeadersBuilder
        arguments:    [@date_helper]

    stadiumBuilder:
        class:        FantasyPro\DataBundle\Builder\StadiumBuilder

    standingBuilder:
        class:        FantasyPro\DataBundle\Builder\StandingBuilder

    teamBuilder:
        class:        FantasyPro\DataBundle\Builder\TeamBuilder

    teamGameStatsBuilder:
        class:        FantasyPro\DataBundle\Builder\TeamGameStatsBuilder
        arguments:    [@date_helper]

    teamSeasonStatsBuilder:
        class:        FantasyPro\DataBundle\Builder\TeamSeasonStatsBuilder
        arguments:    [@date_helper]

    timeFrameBuilder:
        class:        FantasyPro\DataBundle\Builder\TimeFrameBuilder
        arguments:    [@date_helper]

    #persisters
    # These services are responsible for saving the data to the database, they require a Builder to set up the data to persist

    bye_persister:
        class: FantasyPro\DataBundle\Persisters\ByePersister
        arguments: [@doctrine.orm.entity_manager, @byeBuilder]

    dailyFantasyPlayer_persister:
        class: FantasyPro\DataBundle\Persisters\DailyFantasyPlayerPersister
        arguments: [@doctrine.orm.entity_manager, @dailyFantasyPlayerBuilder, @date_helper]

    fantasyDefenceGame_persister:
        class: FantasyPro\DataBundle\Persisters\FantasyDefenseGamePersister
        arguments: [@doctrine.orm.entity_manager, @fantasyDefenseGameBuilder]

    fantasyDefenceSeason_persister:
        class: FantasyPro\DataBundle\Persisters\FantasyDefenseSeasonPersister
        arguments: [@doctrine.orm.entity_manager, @fantasyDefenseSeasonBuilder]

    fantasyDefenceProjectionsByGame_persister:
        class: FantasyPro\DataBundle\Persisters\FantasyDefenseProjectionsByGamePersister
        arguments: [@doctrine.orm.entity_manager, @fantasyDefenceProjectionsByGameBuilder]

    fantasyDefenceProjectionsBySeason_persister:
          class: FantasyPro\DataBundle\Persisters\FantasyDefenseProjectionsBySeasonPersister
          arguments: [@doctrine.orm.entity_manager, @fantasyDefenceProjectionsBySeasonBuilder]

    freeAgent_persister:
        class: FantasyPro\DataBundle\Persisters\FreeAgentPersister
        arguments: [@doctrine.orm.entity_manager, @freeAgentBuilder, @date_helper]

    gameLeagueLeaders_persister:
        class: FantasyPro\DataBundle\Persisters\GameLeagueLeadersPersister
        arguments: [@doctrine.orm.entity_manager, @gameLeagueLeadersBuilder, @date_helper]

    gameStatsBySeason_persister:
        class: FantasyPro\DataBundle\Persisters\GameStatsBySeasonPersister
        arguments: [@doctrine.orm.entity_manager, @gameStatsBySeasonBuilder]

    gameStatsByWeek_persister:
        class: FantasyPro\DataBundle\Persisters\GameStatsByWeekPersister
        arguments: [@doctrine.orm.entity_manager, @gameStatsByWeekBuilder]

    injury_persister:
        class: FantasyPro\DataBundle\Persisters\InjuryPersister
        arguments: [@doctrine.orm.entity_manager, @injuryBuilder]

    news_persister:
        class: FantasyPro\DataBundle\Persisters\NewsPersister
        arguments: [@doctrine.orm.entity_manager, @newsBuilder]

    player_persister:
        class: FantasyPro\DataBundle\Persisters\PlayerPersister
        arguments: [@doctrine.orm.entity_manager, @playerBuilder]

    playergame_persister:
        class: FantasyPro\DataBundle\Persisters\PlayerGamePersister
        arguments: [@doctrine.orm.entity_manager, @playerGameBuilder]

    boxplayergame_persister:
        class: FantasyPro\DataBundle\Persisters\BoxPlayerGamePersister
        arguments: [@doctrine.orm.entity_manager, @boxPlayerGameBuilder]

    playergameprojectedstats_persister:
        class: FantasyPro\DataBundle\Persisters\PlayerGameProjectedStatsPersister
        arguments: [@doctrine.orm.entity_manager, @playerGameProjectedStatsBuilder]

    playerSeason_persister:
        class: FantasyPro\DataBundle\Persisters\PlayerSeasonPersister
        arguments: [@doctrine.orm.entity_manager, @playerSeasonBuilder]

    playerSeasonProjected_persister:
        class: FantasyPro\DataBundle\Persisters\PlayerSeasonProjectedPersister
        arguments: [@doctrine.orm.entity_manager, @playerSeasonProjectedBuilder]

    schedule_persister:
        class: FantasyPro\DataBundle\Persisters\SchedulePersister
        arguments: [@doctrine.orm.entity_manager, @scheduleBuilder]

    score_persister:
        class: FantasyPro\DataBundle\Persisters\ScorePersister
        arguments: [@doctrine.orm.entity_manager, @scoreBuilder]

    scoringdetail_persister:
        class: FantasyPro\DataBundle\Persisters\ScoringDetailPersister
        arguments: [@doctrine.orm.entity_manager, @scoringDetailBuilder]

    scoringplay_persister:
        class: FantasyPro\DataBundle\Persisters\ScoringPlayPersister
        arguments: [@doctrine.orm.entity_manager, @scoringPlayBuilder]

    seasonLeagueLeaders_persister:
        class: FantasyPro\DataBundle\Persisters\SeasonLeagueLeadersPersister
        arguments: [@doctrine.orm.entity_manager, @seasonLeagueLeadersBuilder]

    stadium_persister:
        class: FantasyPro\DataBundle\Persisters\StadiumPersister
        arguments: [@doctrine.orm.entity_manager, @stadiumBuilder]

    standing_persister:
        class: FantasyPro\DataBundle\Persisters\StandingPersister
        arguments: [@doctrine.orm.entity_manager, @standingBuilder]

    team_persister:
        class: FantasyPro\DataBundle\Persisters\TeamPersister
        arguments: [@doctrine.orm.entity_manager, @teamBuilder]

    teamGameStats_persister:
        class: FantasyPro\DataBundle\Persisters\TeamGameStatsPersister
        arguments: [@doctrine.orm.entity_manager, @teamGameStatsBuilder]

    teamSeasonStats_persister:
        class: FantasyPro\DataBundle\Persisters\TeamSeasonStatsPersister
        arguments: [@doctrine.orm.entity_manager, @teamSeasonStatsBuilder]

    timeframe_persister:
        class: FantasyPro\DataBundle\Persisters\TimeFramePersister
        arguments: [@doctrine.orm.entity_manager, @timeFrameBuilder, @date_helper]
