<?php

namespace FantasyPro\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ByeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ByeRepository extends EntityRepository
{
}
