<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * DailyFantasyPlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DailyFantasyPlayerRepository extends \Doctrine\ORM\EntityRepository
{
}
