<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * FantasyDefenseSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FantasyDefenseSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
