<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * FantasyDefenseProjectionsBySeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FantasyDefenseProjectionsBySeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
