<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * FantasyDefenseProjectionsByGameGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FantasyDefenseProjectionsByGameRepository extends \Doctrine\ORM\EntityRepository
{
}
