<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * FreeAgentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FreeAgentRepository extends \Doctrine\ORM\EntityRepository
{
}
