<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * GameStatsBySeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameStatsBySeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
