<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * GameStatsByWeekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameStatsByWeekRepository extends \Doctrine\ORM\EntityRepository
{
}
