<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * GameLeagueLeadersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameLeagueLeadersRepository extends \Doctrine\ORM\EntityRepository
{
}
