<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * InjuryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InjuryRepository extends \Doctrine\ORM\EntityRepository
{
}
