<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * PlayerGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGameRepository extends \Doctrine\ORM\EntityRepository
{
}
