<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * PlayerSeasonProjectedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerSeasonProjectedRepository extends \Doctrine\ORM\EntityRepository
{
}
