<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * PlayerSeasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerSeasonRepository extends \Doctrine\ORM\EntityRepository
{
}
