<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * ScoringPlayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoringPlayRepository extends \Doctrine\ORM\EntityRepository
{
}
