<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * ScoringDetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScoringDetailRepository extends \Doctrine\ORM\EntityRepository
{
}
