<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * SeasonLeagueLeadersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeasonLeagueLeadersRepository extends \Doctrine\ORM\EntityRepository
{
}
