<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * StandingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StandingRepository extends \Doctrine\ORM\EntityRepository
{
}
