<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * TeamSeasonStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamSeasonStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
