<?php

namespace FantasyPro\DataBundle\Entity;

/**
 * TeamGameStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamGameStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
