<?php

namespace FantasyPro\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeframeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeFrameRepository extends EntityRepository
{
    /**
     * @return String
     */
    public function getSeasonType()
    {
        $timeFrame = $this->currentTimeFrame();

        return $timeFrame->getSeasonType();
    }

    /**
     * @return int
     */
    public function getCurrentSeason()
    {
        $timeFrame = $this->currentTimeFrame();

        return $timeFrame->getSeason();
    }

    /**
     * @return int
     */
    public function getLastSeason()
    {
        $timeFrame     = $this->currentTimeFrame();
        $currentSeason = $timeFrame->getSeason();
        $lastSeason    = $currentSeason - 1;

        return $lastSeason;
    }

    /**
     * @return String
     */
    public function getCurrentWeek()
    {
        $timeFrame = $this->currentTimeFrame();

        return $timeFrame->getWeek();
    }

    /**
     * @return TimeFrame
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function currentTimeFrame()
    {
        return $this->createQueryBuilder( 'q' )
                    ->andWhere( 'q.startDate < :startdate AND q.endDate > :startdate' )
                    ->setParameter( 'startdate', new \DateTime() )
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
