<?php

namespace FantasyPro\DataBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TimeframeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeFrameRepository extends EntityRepository
{
    /**
     * @return String
     */
    public function getSeasonType()
    {
        $timeFrame = $this->getCurrentTimeFrame();

        return $timeFrame->getSeasonType();
    }

    /**
     * @return int
     */
    public function getCurrentSeason()
    {
        $timeFrame = $this->getCurrentTimeFrame();

        return $timeFrame->getSeason();
    }

    /**
     * @return int
     */
    public function getLastSeason()
    {
        $timeFrame     = $this->getCurrentTimeFrame();
        $currentSeason = $timeFrame->getSeason();
        $lastSeason    = $currentSeason - 1;

        return $lastSeason;
    }

    /**
     * @return String
     */
    public function getCurrentWeek()
    {
        $timeFrame = $this->getCurrentTimeFrame();

        return $timeFrame->getWeek();
    }

    /**
     * @return TimeFrame
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getCurrentTimeFrame()
    {
        $date = new \DateTime();
        return $this->createQueryBuilder( 'q' )
                    ->Where( 'q.startDate < :date1 AND q.endDate > :date2' )
                    ->setParameter( 'date1', $date )
                    ->setParameter( 'date2', $date )
                    ->getQuery()
                    ->getOneOrNullResult();
    }
}
